/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BibleStudyRouteImport } from './routes/bible-study'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as ProverbialDigestRouteImport } from './routes/proverbial-digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleStudyRoute = BibleStudyRouteImport.update({
  id: '/bible-study',
  path: '/bible-study',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const ProverbialDigestRoute = ProverbialDigestRouteImport.update({
  id: '/proverbial-digest',
  path: '/proverbial-digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bible-study': typeof BibleStudyRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/proverbial-digest': typeof ProverbialDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bible-study': typeof BibleStudyRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/proverbial-digest': typeof ProverbialDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bible-study': typeof BibleStudyRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/proverbial-digest': typeof ProverbialDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bible-study'
    | '/dashboard'
    | '/gallery'
    | '/giving'
    | '/proverbial-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bible-study'
    | '/dashboard'
    | '/gallery'
    | '/giving'
    | '/proverbial-digest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bible-study'
    | '/dashboard'
    | '/gallery'
    | '/giving'
    | '/proverbial-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BibleStudyRoute: typeof BibleStudyRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  GivingRoute: typeof GivingRoute
  ProverbialDigestRoute: typeof ProverbialDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-study': {
      id: '/bible-study'
      path: '/bible-study'
      fullPath: '/bible-study'
      preLoaderRoute: typeof BibleStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proverbial-digest': {
      id: '/proverbial-digest'
      path: '/proverbial-digest'
      fullPath: '/proverbial-digest'
      preLoaderRoute: typeof ProverbialDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BibleStudyRoute: BibleStudyRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  GivingRoute: GivingRoute,
  ProverbialDigestRoute: ProverbialDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
